import Image from "next/image";
import Link from "@/components/DocumentLink";
import EditorialPage from "@/components/content/EditorialPage";
import { metadataFor } from "@/seo/metadata";
import styles from "@/style/content/editorial-page.module.css";
import inner from "@/style/page/inner.module.css";

const storyChapters = [
  { title: "Open the station", image: "/images/guides/steam-4.webp", alt: "Drag'n Wash station during the opening call and customer arrival", text: "Answer the phone, finish the window conversation and open the gate when the objective points you there." },
  { title: "Learn the care loop", image: "/images/guides/steam-9.webp", alt: "A dragon being cleaned during the first care loop", text: "Prepare the water, wet the sponge, work across visible dirt, reposition the dragon and rinse before checking the next request." },
  { title: "Handle changing visits", image: "/images/guides/steam-5.webp", alt: "A later Drag'n Wash story visit with different lighting", text: "Do not expect every arrival to repeat the first wash. Later visits can add debris, first aid, dialogue or scene-specific equipment." },
  { title: "Track meaningful choices", image: "/images/guides/steam-1.webp", alt: "Close character interaction during a relationship choice", text: "Note the responses that visibly matter, finish the run and change one uncertain choice next time instead of guessing at a hidden score." },
];

export const metadata = metadataFor("walkthrough", "/walkthrough");

export default function WalkthroughPage() {
  return <EditorialPage
    variant="checklist"
    path="/walkthrough"
    reviewedAt="2026-09-22"
    breadcrumbs={[{ label: "Guides", href: "/guides" }]}
    eyebrow="COMPLETE STORY FLOW"
    keyword="DRAG'N WASH WALKTHROUGH"
    title="Drag'n Wash Walkthrough – From the First Phone Call to the Credits"
    displayTitle="FULL PLAYTHROUGH"
    subtitle="From the First Phone Call to the Credits"
    lead="Follow the shared story without losing your place: open the station, finish each care task, keep up with all three dragons and know what to check before starting another ending."
    image="/images/guides/steam-9.webp"
    imageAlt="A dragon being cleaned during a Drag'n Wash playthrough"
    answer={<><p>Start with the ringing phone and front gate, learn the basic wash loop, then slow down when later visits add dialogue and scene-specific care. Read the current objective, finish the task in front of you and note any response you may want to change on another run.</p><p className={styles.source}><span className="badge muted">LIGHT STORY SPOILERS</span> The opening steps are practical instructions. Later route details stay cautious where the game does not show a clear cause and effect.</p></>}
    sections={[
      { id: "premise", title: "Your job at the wash station", content:<><p>You run a soap-and-wash service built for dragons. What begins as hands-on cleaning gradually becomes conversation, care and more personal requests as the customers return. The game lists three endings and estimates approximately 90 minutes of content for each ending.</p><p>Alexander, Ryan and Conrad all appear in one shared run. You can pay closer attention to one relationship, but you are not choosing three isolated campaigns from the title screen.</p><div className={styles.cards}><Link href="/#adult-content"><strong>Before you buy</strong><span>Adult-content scope, official stores and platform questions</span></Link><Link href="/#gameplay"><strong>Gameplay overview</strong><span>How washing, conversation and story progression connect</span></Link></div></> },
      { id: "before-starting", title: "Before starting a run", content:<><ul><li>Update the game before using an old workaround; the September 2026 hotfix changed several interactions.</li><li>Choose a progress slot, but do not assume it is a manual save at every dialogue choice.</li><li>Use the current on-screen prompt for exact input buttons.</li><li>Keep short notes if you want to compare relationship choices on another run.</li></ul><div className={styles.cards}><Link href="/guides/controls"><strong>Controls & comfort</strong><span>Controller, invert Y, motion and Unstick</span></Link><Link href="/endings#replay-all-endings"><strong>Endings & replay</strong><span>Progress slots, credits and another run</span></Link></div></> },
      { id: "tools", title: "Tools you will use", content:<><table className={styles.table}><thead><tr><th>Tool or item</th><th>Role</th><th>Switch when</th></tr></thead><tbody><tr><td>Bucket and water</td><td>Prepare and refresh the wet cleaning loop</td><td>The sponge stops registering</td></tr><tr><td>Sponge</td><td>Remove visible dirt in broad passes</td><td>The surface is clean or the request changes</td></tr><tr><td>Sprayer</td><td>Rinse soap and loosened grime</td><td>Soap clears or the objective advances</td></tr><tr><td>Hands and later items</td><td>Contextual interactions named or exposed by the scene</td><td>The current prompt requests something else</td></tr></tbody></table><p>The official hotfix also names a medkit and a mount in later scenes, but it does not publish universal unlock thresholds. Follow the current request rather than a fan-made tool score.</p><Link href="/guides/washing-tools">Open the complete tool reference →</Link></> },
      { id: "step-by-step", title: "A complete run in four stages", content:<><div className={inner.storyChapters}>{storyChapters.map((chapter, index)=><article key={chapter.title}><Image src={chapter.image} width={600} height={338} alt={chapter.alt}/><div><span className="eyebrow">CHAPTER {String(index + 1).padStart(2, "0")}</span><h3>{chapter.title}</h3><p>{chapter.text}</p></div></article>)}</div><p>Need every interaction in the opening shift? Use the <Link href="/guides/beginner-guide">Beginner Guide</Link>. This walkthrough follows the whole run and links out when a tool, wash problem or character needs more detail.</p></> },
      { id: "wash-loop", title: "The wash loop in one glance", content:<><div className={inner.processFlow}><span>Fill</span><span>Wet</span><span>Scrub</span><span>Reposition</span><span>Rinse</span><span>Inspect</span><span>Finish request</span></div><p>The clean indicator and the scene objective are related but not identical. A full-looking bar can still leave a small mark, soap layer or separate interaction. Stop repeating one motion and diagnose which state you are in.</p></> },
      { id: "story-flow", title: "What changes after the first wash", content:<><p>Later visits build on the same basic rhythm but can add debris removal, care items, different dialogue and interactions that are not ordinary washing. A useful walkthrough habit is to separate the mechanical state from the story state:</p><ol className={inner.timeline}><li><strong>Customer arrival</strong><span>Finish the window, gate or conversation state.</span></li><li><strong>Preparation</strong><span>Identify the requested care task before collecting tools.</span></li><li><strong>Wash or special task</strong><span>Use visual and prompt feedback; later visits do not all begin with soap.</span></li><li><strong>Conversation and relationship choice</strong><span>Record a meaningful response if you want to compare a replay.</span></li><li><strong>Dismissal or next objective</strong><span>Wait for the scene to close before assuming progress is stuck.</span></li></ol><p>Player videos show leaves, first aid, a late-night visit, a picnic and later contextual equipment. They are useful clues for finding a scene, but exact order and route effects may still change with the current build.</p><Link href="/dragons#story-moments">Compare dragon visits and story moments →</Link></> },
      { id: "dragons", title: "The three dragons in the shared run", content:<><div className={styles.cards}><Link href="/dragons/alexander"><strong>Alexander</strong><span>Tall purple dragon; identity and late-dialogue observations</span></Link><Link href="/dragons/ryan"><strong>Ryan</strong><span>Pale dragon; picnic scene and relationship reports</span></Link><Link href="/dragons/conrad"><strong>Conrad</strong><span>Red dragon named in official hotfix notes</span></Link><Link href="/romance"><strong>Relationship choices</strong><span>What players observed and what remains uncertain</span></Link></div><p>Conrad is named directly in official patch notes. Alexander and Ryan are established community names, so their pages distinguish common player usage from details confirmed by the developer.</p></> },
      { id: "choices", title: "Relationship choices and route discipline", content:<><p>The safest way to learn route structure is to change one meaningful response between runs. Do not alter every conversation, cleaning technique and request at once and then attribute the outcome to one guessed affection value.</p><table className={styles.table}><thead><tr><th>Record</th><th>Why</th><th>Do not assume</th></tr></thead><tbody><tr><td>Character and scene</td><td>Locates the branch in the shared run</td><td>That every visit is route-exclusive</td></tr><tr><td>Exact response</td><td>Makes a replay comparable</td><td>That wording maps to a numeric score</td></tr><tr><td>Later dialogue change</td><td>Shows an observable consequence</td><td>That it alone caused the ending</td></tr><tr><td>Final outcome</td><td>Connects the test to a result</td><td>That fan-made ending names are official</td></tr></tbody></table></> },
      { id: "playtime", title: "How long a full Drag'n Wash playthrough takes", content:<><p>The developer describes approximately 90 minutes of content per ending. Treat that as a content estimate rather than a timer: reading every line, inspecting the station or recovering a stuck wash can make a first run longer, while a focused replay may be shorter.</p><p>The released experience is a compact story playthrough. Job Mode, endless washing and a chapter gallery appear in player requests and fan pages, but they are not treated here as shipped features. Check the <Link href="/updates#future-of-drag-n-wash">development timeline</Link> before planning around them.</p></> },
      { id: "endings", title: "Approaching an ending", content:<><p>The developer confirms three endings, while filmed choices now establish route locks for Conrad and Ryan. Before the late part of a run, record which relationship you opened and how Alexander responds. Complete the run before testing a different variable.</p><p>If Continue returns to credits, do not assume the completed slot is a gallery or chapter selector. Preserve your notes and start another slot or run for the next comparison.</p><div className={styles.cards}><Link href="/endings#ending-routes"><strong>Ending routes</strong><span>Conrad, Ryan, pairing and Alexander branches</span></Link><Link href="/endings#replay-all-endings"><strong>Replay all three endings</strong><span>Progress slots, credits and controlled comparisons</span></Link></div></> },
      { id: "completion-check", title: "When the wash will not complete", content:<ol><li>Read the active request.</li><li>Confirm the sponge is wet and the rinse pass removed soap.</li><li>Inspect the far side, tail, neck edges and limbs from a new angle.</li><li>Put down the tool and look for dialogue, debris or another interaction.</li><li>Use Unstick Kobold only if movement or interaction is actually locked.</li><li>Restart the scene only after the safer checks fail.</li></ol> },
      { id: "pitfalls", title: "Common walkthrough pitfalls", content:<><table className={styles.table}><thead><tr><th>Symptom</th><th>Likely category</th><th>Next page</th></tr></thead><tbody><tr><td>Clean bar appears full</td><td>Missed spot, rinse or waiting request</td><td><Link href="/troubleshooting/wash-progress">Wash-progress decision tree →</Link></td></tr><tr><td>Cannot move or interact</td><td>Possible softlock</td><td><Link href="/troubleshooting/stuck-softlock">Recovery steps →</Link></td></tr><tr><td>Long first boot</td><td>Shader preloading or launch issue</td><td><Link href="/troubleshooting/launch-performance">Launch checks →</Link></td></tr><tr><td>Cannot find Job Mode or gallery</td><td>Possibly an unshipped feature request</td><td><Link href="/updates#future-of-drag-n-wash">Development status →</Link></td></tr></tbody></table></> },
      { id: "evidence", title: "Before following an exact route claim", content:<><p>The opening sequence can be repeated consistently, but the game does not publish numeric romance thresholds or a complete ending-route chart. Treat any guide that promises an exact hidden score with caution.</p><p>Patch changes can also alter a scene or workaround. If a step behaves differently, update the game first and check the <Link href="/updates">latest changes</Link> before restarting your run.</p></> },
    ]}
    related={[{label:"Beginner guide",href:"/guides/beginner-guide"},{label:"How to wash",href:"/guides/how-to-wash"},{label:"Endings and replay",href:"/endings"},{label:"Dragon visits",href:"/dragons#story-moments"}]}
  />;
}
