import type { ReactNode } from "react";
import EditorialPage from "@/components/content/EditorialPage";
import { contactEmail as email } from "@/config/site";

type LegalKind = "privacy" | "terms" | "copyright" | "about" | "contact";

type LegalContent = {
  eyebrow: string;
  keyword: string;
  title: string;
  subtitle: string;
  lead: string;
  answer: ReactNode;
  sections: { id: string; title: string; content: ReactNode }[];
};

const content: Record<LegalKind, LegalContent> = {
  privacy: {
    eyebrow: "LEGAL & PRIVACY",
    keyword: "DRAG'N WASH LEGAL",
    title: "PRIVACY POLICY",
    subtitle: "How this fan guide handles visitor information",
    lead: "This policy explains the limited information that may be processed when you browse the site, follow an external link or email us directly.",
    answer: <><p><strong>Effective and last reviewed: September 2026.</strong> This policy applies to dragnwash.com and explains what information may be handled when you read a page, open an external link or contact us by email.</p><p>You can use the guide without an account, profile, contact form or paid subscription. The current site does not run advertising pixels, behavioral advertising or a first-party analytics service, and it does not ask for gameplay saves, payment details or sensitive personal information.</p></>,
    sections: [
      { id: "scope", title: "Who is responsible and what this policy covers", content: <><p>Drag&apos;n Wash Guide is the publisher responsible for the information-handling choices described here. Privacy questions and requests can be sent to <a href={`mailto:${email}`}>{email}</a>. No separate data protection officer has been appointed for this small fan resource.</p><p>This policy covers visits to this domain and direct email sent to the published address. It does not cover Steam, itch.io, GitHub, social networks, community forums, the game itself or another website reached through a link. Those services decide their own collection, legal bases, retention and security practices.</p></> },
      { id: "information", title: "Information we may receive", content: <><p><strong>Technical request data.</strong> The hosting, content-delivery or security layer may record an IP address, approximate network region, browser and operating-system information, requested URL, referring page, request time, response status, transferred bytes and security signals. This is ordinary server traffic data; we do not use it to build a named player profile.</p><p><strong>Information you send.</strong> An email can contain your address, display name, message, timestamps, page URLs, platform and game-version details, and any screenshots or files you choose to attach. We receive that information directly from you. Do not send passwords, payment information, identity documents, license keys, private account credentials or data about another person that you are not authorized to share.</p><p><strong>Information we do not request.</strong> There is no registration, comment area, public profile, checkout, newsletter or user-upload system. We do not intentionally collect precise location, payment-card data, biometric information or government identifiers through the website.</p></> },
      { id: "purposes", title: "Why information is used and the legal basis", content: <><p>Technical request data may be processed to deliver pages, balance traffic, prevent abuse, investigate errors, maintain security and understand whether a route is functioning. Where laws such as the UK GDPR or EU GDPR apply, these activities are generally based on our legitimate interests in operating a secure, reliable informational website. We balance those interests against the limited nature of the data and the rights of visitors.</p><p>Email information is used to reply to the sender, verify a correction, investigate accessibility or technical feedback, handle a privacy request, or assess a copyright notice. The basis may be taking steps at your request, legitimate interests in maintaining accurate content and protecting rights, or compliance with a legal obligation where one applies.</p><p>We do not use contact emails for unrelated marketing, automated eligibility decisions or behavioral profiling. We do not sell or rent personal information and do not treat an email as consent to a mailing list.</p></> },
      { id: "cookies", title: "Cookies, browser storage and analytics", content: <><p>The current site does not intentionally set first-party analytics, advertising or preference cookies and does not write a visitor profile to localStorage or sessionStorage. Reading the guide does not require a cookie banner or an account session under the current implementation.</p><p>A hosting, network-security or content-delivery provider may use a strictly necessary identifier to route traffic, limit abuse or protect the service. Browser settings can block or remove cookies, but doing so may affect a provider&apos;s security checks. If optional analytics, advertising or new browser storage is introduced later, this page and any consent controls will be updated before that new use begins where required.</p><p>Because the site does not currently conduct cross-site behavioral tracking, it does not respond differently to “Do Not Track” or Global Privacy Control signals. This statement will be revisited if tracking practices change.</p></> },
      { id: "sharing", title: "Service providers, disclosures and international processing", content: <><p>Limited information may be available to vendors that provide hosting, content delivery, network security, error handling or email delivery. They receive only the information needed to perform those functions and may operate from a country different from yours. Applicable contractual or legal safeguards should be used where a restricted international transfer requires them.</p><p>Information may also be disclosed when reasonably necessary to comply with law, respond to valid legal process, protect users or the service, investigate fraud or security incidents, or establish, exercise or defend legal claims. We do not disclose a visitor list to the game developer merely because this is a fan site.</p><p>External links are ordinary links rather than embedded third-party widgets. The destination may receive your IP address and standard request information when you choose to open it. Review that service&apos;s own privacy notice before signing in, purchasing or uploading anything.</p></> },
      { id: "retention", title: "Retention and deletion", content: <><p>We aim to keep technical logs only for the period reasonably needed for delivery, security, incident investigation and provider operations. Exact infrastructure retention can depend on the hosting or security provider. Aggregated information that no longer identifies a person may be kept longer.</p><p>Routine email is kept while the question or correction is being handled and may then be deleted when it no longer serves an operational, evidentiary or legal purpose. Privacy, security and copyright correspondence may be retained longer when needed to document the request and our response. Backup copies can persist for a limited recovery cycle before being overwritten.</p></> },
      { id: "rights", title: "Your privacy rights", content: <><p>Depending on where you live and which law applies, you may have rights to be informed; request access to personal information; correct inaccurate information; request deletion or restriction; object to processing based on legitimate interests; withdraw consent where consent is used; and receive portable information where portability applies. You may also complain to the data-protection authority responsible for your location.</p><p>Send a request to <a href={`mailto:${email}`}>{email}</a> with the subject “Privacy Request.” State the right you wish to exercise and enough information to locate your earlier correspondence. We may ask for proportionate verification so information is not disclosed to the wrong person. A request can be limited or refused where the law permits, including where records must be retained or the requester cannot be verified; if so, we will explain the reason when required.</p></> },
      { id: "children", title: "Children and adult-oriented game content", content: <><p>This is a general-audience fan guide for an adult-rated game and is not directed to children under 13 or the minimum digital-consent age that applies in their location. We do not knowingly collect personal information from children through accounts, comments or forms because those features do not exist.</p><p>If a parent or guardian believes a child sent personal information to the contact address, they can email us with enough detail to locate the message. We will review and delete it where appropriate and legally permitted.</p></> },
      { id: "security", title: "Security and data minimization", content: <><p>We reduce risk by collecting little information, avoiding public user submissions and limiting contact to email. Reasonable technical and organizational safeguards should protect data in transit and within the services used to operate the site. No email or internet service is completely secure, so only send information necessary for the request.</p><p>If a security incident creates a legally reportable risk, affected people and authorities will be notified as required by applicable law.</p></> },
      { id: "changes", title: "Policy changes and contact", content: <><p>We may revise this notice when site features, providers or legal requirements change. Material changes will be reflected by a new effective date and, where appropriate, a prominent notice. A new policy applies prospectively from its stated date rather than silently changing how an earlier email was handled.</p><p>Questions, objections and privacy requests can be sent to <a href={`mailto:${email}`}>{email}</a>. This policy describes the current site configuration; it is not a promise that every third-party network provider uses identical terminology.</p></> },
    ],
  },
  terms: {
    eyebrow: "LEGAL & USE",
    keyword: "DRAG'N WASH LEGAL",
    title: "TERMS OF SERVICE",
    subtitle: "Rules for using this independent fan resource",
    lead: "These terms describe permitted use of the guide, the limits of its gameplay information and the responsibilities attached to external links.",
    answer: <><p><strong>Effective and last reviewed: September 2026.</strong> These terms apply to your use of dragnwash.com. By accessing the site, you agree to these terms and the Privacy Policy. If you do not agree, do not continue using the site.</p><p>This is an independent informational fan guide. It is not the game, a storefront, official customer support or a service operated by Gator Dragon Games.</p></>,
    sections: [
      { id: "eligibility", title: "Eligibility and adult-content notice", content: <><p>You must be legally able to agree to these terms. The guide discusses a game marketed with adult content. You are responsible for following the age rules, workplace or school policies, platform terms and laws that apply where you access the site or game.</p><p>The site uses non-graphic presentation on general navigation pages, but written pages can discuss mature themes. A link or content warning is informational and does not replace your own decision about whether the material is appropriate for you.</p></> },
      { id: "license", title: "Limited permission to use the site", content: <><p>Subject to these terms, you receive a limited, non-exclusive, non-transferable and revocable permission to access public pages for personal, non-commercial reference. You may save an ordinary browser copy, print a page for personal use, share a normal link and quote a brief portion for criticism or discussion with clear attribution and a link to the page.</p><p>This permission does not transfer ownership. It does not authorize republication of complete articles, bulk copying, mirroring, sale of our text or design, removal of notices, use of the site&apos;s presentation to impersonate us, or creation of a substitute guide assembled substantially from our content.</p></> },
      { id: "prohibited", title: "Prohibited conduct", content: <><p>You may not use the site to break the law or another person&apos;s rights; interfere with availability; probe or bypass security; introduce malicious code; overload the service; scrape personal contact information; harvest email addresses; misrepresent affiliation; or use automated requests at a rate that disrupts ordinary visitors.</p><p>You may not use information here to distribute pirated copies, stolen keys, unauthorized explicit media, malware or files falsely presented as official mods. Search-engine crawling that follows published directives and reasonable indexing practices is not prohibited by this paragraph.</p></> },
      { id: "editorial", title: "Editorial information, spoilers and changing builds", content: <><p>Guides reflect the sources, testing and game build available at the stated review date. Patches can change interactions, controls, route behavior, compatibility and known issues. Store prices, regional access and third-party availability can change without notice. Community findings are labeled when they are not confirmed as official facts.</p><p>We aim for accurate, useful writing but do not warrant that every instruction is complete, current or suitable for every device, save file or player choice. Spoiler labels reduce accidental exposure but cannot guarantee that every reader will consider the same detail a spoiler.</p></> },
      { id: "technical", title: "Troubleshooting, mods and local files", content: <><p>Any troubleshooting step, configuration change or third-party modification is used at your own discretion. Back up saves and files before making changes; read the project owner&apos;s current documentation; and use official stores or identified project releases. We do not instruct visitors to disable security software or obtain unknown executables.</p><p>We are not responsible for corrupted saves, lost progress, incompatibility, account action, hardware damage or security incidents caused by a third-party file or a change you choose to make. If a guide conflicts with an official platform or developer instruction, stop and use the official instruction.</p></> },
      { id: "external", title: "External links, stores and transactions", content: <><p>Links to Steam, itch.io, GitHub, developer posts and community discussions are provided for verification or convenience. We do not control those services, their content, security, availability or privacy practices. A link does not mean that every statement, download or user comment on the destination is endorsed.</p><p>You purchase the game, request a refund, manage an account or download a third-party project directly from the relevant provider. We are not the seller or contracting party, do not process payment, cannot grant a license or refund, and cannot guarantee regional availability or future support.</p></> },
      { id: "submissions", title: "Emails, corrections and feedback", content: <><p>If you send a correction or suggestion, you confirm that you have the right to share it and that it does not contain unlawful material or another person&apos;s confidential information. You retain ownership of your original message. You allow us to use the factual information and ideas it contains to investigate, correct and improve the guide without payment or attribution, unless we expressly agree otherwise.</p><p>Do not send unreleased builds, leaked material, private messages, explicit files, passwords or personal data unrelated to the request. Email does not create a confidential, fiduciary, professional or employment relationship.</p></> },
      { id: "ownership", title: "Intellectual property and fan-site status", content: <><p>Drag&apos;n Wash, its characters, artwork, screenshots, game code, names and related marks belong to their respective owners. Their use here is limited to identification, criticism, comment, reporting and instruction. No sponsorship, license or endorsement by the rights holders is claimed.</p><p>Our original prose, organization, annotations, custom brand artwork and site design are protected separately. Additional details and the notice process appear on the Copyright page. Nothing in these terms restricts rights you may have under copyright exceptions, fair use, fair dealing or other mandatory law.</p></> },
      { id: "privacy", title: "Privacy", content: <p>The Privacy Policy explains the limited technical information and email correspondence that may be processed. It forms part of these terms. The site currently has no account, public-comment, checkout or newsletter system.</p> },
      { id: "disclaimer", title: "Disclaimers", content: <><p>To the maximum extent permitted by applicable law, the site is provided “as is” and “as available,” without warranties of accuracy, completeness, merchantability, fitness for a particular purpose, non-infringement or uninterrupted availability. Some jurisdictions do not allow particular warranty exclusions, so an exclusion applies only to the extent lawful for you.</p><p>The website provides fan commentary and general technical information, not legal, medical, financial or official product-support advice. Nothing here promises a particular ending, game experience, device result or continued availability of a third-party project.</p></> },
      { id: "liability", title: "Limitation of liability", content: <><p>To the maximum extent permitted by law, the site operator and contributors will not be liable for indirect, incidental, special, consequential or punitive loss; loss of data, progress, revenue or opportunity; or harm arising from reliance on a guide, unavailable content, a third-party service or a user-installed modification.</p><p>Nothing in these terms excludes liability that cannot legally be excluded, including liability that mandatory consumer law preserves. Your statutory consumer rights, if any, are not waived.</p></> },
      { id: "administration", title: "Changes, suspension and general terms", content: <><p>We may correct, reorganize, suspend or discontinue a page or the site, and may restrict abusive automated traffic. We may update these terms prospectively; the effective date identifies the current version. Material changes may be highlighted where practical.</p><p>If a provision is unenforceable, the remaining provisions continue to apply and the affected provision will be limited to the minimum extent necessary. A failure to enforce a provision once is not a permanent waiver. These terms, together with the Privacy and Copyright pages, form the entire website-use agreement to the extent permitted by law. Mandatory local law remains applicable where it cannot be displaced.</p><p>Questions about these terms can be sent to <a href={`mailto:${email}`}>{email}</a>.</p></> },
    ],
  },
  copyright: {
    eyebrow: "LEGAL & OWNERSHIP",
    keyword: "DRAG'N WASH LEGAL",
    title: "COPYRIGHT",
    subtitle: "Game ownership, fan commentary and notice requests",
    lead: "This page separates the game owner's material from the original writing and design created for this independent player guide.",
    answer: <><p><strong>Effective and last reviewed: September 2026.</strong> Drag&apos;n Wash, its characters, game artwork, code, audio, screenshots and associated marks remain the property of their respective owners. This independent website does not claim ownership of the game or official branding.</p><p>This page explains how game material is used editorially, what belongs to this site and how a rights holder can request review of specific material.</p></>,
    sections: [
      { id: "ownership", title: "Ownership and trademarks", content: <><p>The game developer, publisher and other applicable rights holders retain their rights in the game and official promotional material. Product names, character names, storefront marks and logos are used only to identify the subjects being discussed. Their appearance does not imply partnership, sponsorship, approval or endorsement.</p><p>The site name and custom fan-site artwork are not presented as official game branding. Visitors should use the linked official storefronts and developer channels when they need an authoritative purchase, license or support source.</p></> },
      { id: "game-material", title: "How game material is used", content: <><p>Selected screenshots and short factual references appear next to walkthroughs, criticism, troubleshooting, character analysis and version reporting. Images are captioned and organized to explain a specific mechanic, scene, issue or editorial point. The site does not offer game files, extracted asset packs, scene downloads, soundtrack copies or a substitute for purchasing and experiencing the game.</p><p>We aim to use only the amount reasonably useful for the editorial purpose, avoid unnecessary high-resolution redistribution and link readers toward legitimate game sources. Where applicable, such use may be evaluated under fair use, fair dealing or another copyright exception. Those doctrines are fact-specific; this page does not claim that every possible reuse is automatically lawful.</p></> },
      { id: "fair-use", title: "Fair-use and editorial factors", content: <><p>For United States fair-use analysis, Section 107 identifies four non-exclusive factors: the purpose and character of the use; the nature of the copyrighted work; the amount and substantiality used; and the effect on the potential market. Commentary or instruction is not automatically fair merely because it is non-commercial, and no fixed percentage guarantees permission.</p><p>Our editorial approach is to add explanation and context, select material relevant to that explanation and avoid market substitution. Rights can differ by country. A person who wants to reuse game-owned media must conduct their own analysis or obtain permission from the relevant owner.</p></> },
      { id: "site-material", title: "Original material created for this site", content: <><p>Unless otherwise identified, the original prose, page organization, annotations, tables, diagrams, troubleshooting decisions, custom logo and site-specific visual treatment are protected by applicable copyright law. A factual game mechanic is not made ours merely because we describe it, but our particular expression and presentation may be protected.</p><p>You may share a public page link and quote a brief passage with clear identification of Drag&apos;n Wash Guide and a link to the source page. You may not reproduce complete articles, mirror substantial sections, strip notices, sell copied text or present our original work as your own without written permission. Rights provided by mandatory law remain unaffected.</p></> },
      { id: "permission", title: "Permission requests", content: <><p>For proposed reuse of material created by this site, email <a href={`mailto:${email}`}>{email}</a> with the exact material, page URL, intended use, audience, distribution method and whether the use is commercial. A request is not approved until written permission is received.</p><p>We cannot license screenshots, characters, music, game text or other material owned by the game&apos;s rights holders. Contact the relevant owner for those permissions.</p></> },
      { id: "notices", title: "Copyright infringement notice", content: <><p>If you are a copyright owner or authorized agent and believe specific material on this domain infringes your rights, send a written notice to <a href={`mailto:${email}`}>{email}</a> with the subject “Copyright Notice.” To help us identify and assess the claim, include:</p><ol><li>Your physical or electronic signature.</li><li>Identification of the copyrighted work, or a representative list if multiple works on the site are involved.</li><li>The exact URL and a clear description of the material claimed to infringe so it can be located.</li><li>Your name, mailing address, telephone number and email address.</li><li>A statement that you have a good-faith belief the disputed use is not authorized by the owner, its agent or the law.</li><li>A statement that the notice is accurate and, under penalty of perjury, that you are the copyright owner or authorized to act for the owner.</li></ol><p>Knowingly making a material misrepresentation in a notice can have legal consequences. Consider whether an exception, license or other authorization applies before sending a notice.</p></> },
      { id: "review", title: "How a notice is reviewed", content: <><p>We may acknowledge receipt, request missing information, temporarily restrict access while investigating, contact the person or source associated with the material where appropriate, and remove, replace or restore material based on the available information. We aim to respond to a sufficiently detailed, good-faith notice without unnecessary delay but do not promise a fixed resolution time.</p><p>The email above is the site&apos;s operational rights-contact address. Listing it here does not state that it has been registered with the U.S. Copyright Office as a designated DMCA agent or that the site qualifies for a particular statutory safe harbor.</p></> },
      { id: "counter", title: "Mistake or misidentification", content: <><p>If material you supplied or rights you hold are affected by a removal and you believe the action resulted from mistake or misidentification, contact the same address. Identify the removed material and its former location, explain the basis for your position, and provide reliable contact information. We may provide additional counter-notice requirements if a formal statutory process applies.</p><p>Do not make statements under penalty of perjury unless you understand them and they are true. You may wish to obtain independent legal advice before submitting a formal notice or counter-notice.</p></> },
      { id: "links", title: "Linking, citations and third-party material", content: <><p>Ordinary linking to a public page is welcome and does not transfer a license to republish its contents. Short quotations should name the page and link directly to it. Screenshots or text credited to a third party remain subject to that party&apos;s rights even when they appear within our commentary.</p><p>Copyright questions about material hosted on Steam, itch.io, GitHub, a forum or another external service must be directed to that service or rights holder. We cannot remove or license content that is not hosted on this domain.</p></> },
    ],
  },
  about: {
    eyebrow: "ABOUT THE SITE",
    keyword: "DRAG'N WASH GUIDE",
    title: "ABOUT US",
    subtitle: "A practical field manual made for players",
    lead: "We organize walkthroughs, character notes, endings, fixes and changing feature status so players can solve a problem without sorting through conflicting claims.",
    answer: <><p><strong>Last reviewed: September 2026.</strong> This is an independent Drag&apos;n Wash fan site written for the player standing in the wash bay: what to do next, what a prompt means, what changed in a patch and which popular claim still needs proof.</p><p>We are not Gator Dragon Games and do not represent the developer, publisher, storefronts or third-party mod authors.</p></>,
    sections: [
      { id: "purpose", title: "Why this guide exists", content: <><p>Drag&apos;n Wash combines tactile cleaning, character conversations and branching story content. The useful answer to a player&apos;s question may be spread across an official store description, patch post, developer reply, current-build observation and community report. That fragmentation makes it easy for an old workaround or confident guess to be repeated as fact.</p><p>We bring those questions into focused pages so a new player can complete the opening shift, a returning player can understand what changed, and a stuck player can try the least destructive fix first.</p></> },
      { id: "audience", title: "Who the site is for", content: <><p>The field manual serves first-time players, returning players comparing routes, people troubleshooting a current build and prospective buyers checking platforms, length or mature-content context. General pages use non-graphic imagery, while pages that discuss adult themes or spoilers are labeled according to their subject.</p><p>The site is not directed to children, does not host explicit downloads and is not a replacement for the game. It is designed to help legitimate players understand and use a product obtained from an authorized source.</p></> },
      { id: "coverage", title: "What we cover", content: <><p>The current guide includes a full walkthrough; five focused wash and control guides; profiles for Alexander, Ryan and Conrad; relationship and ending guidance; official screenshots; store, platform and adult-content answers; mods and localization; a dated update timeline; and symptom-first troubleshooting.</p><p>Gameplay, purchase information, screenshots and content questions live in focused sections on the home page, while deeper subjects keep their own pages. We do not create a separate thin page for every search variation, unconfirmed character, rumored mode or minor question. A subject receives its own page when it has a distinct player need and enough reliable information to support it.</p></> },
      { id: "standards", title: "Evidence and editorial standards", content: <><p>We separate four things that are often mixed together: information published by the developer or storefront; behavior visible in a current game build; a developer reply that may be informal or time-sensitive; and a community report that still needs reproduction. Labels and wording should make that distinction visible.</p><p>We avoid invented affection scores, unofficial “true ending” names, fabricated unlock requirements and precise route formulas that cannot be supported. When credible reports conflict, the page should explain the conflict rather than selecting the more exciting claim.</p><p>Patch-sensitive pages display a reviewed date. Meaningful corrections should update the affected page and its sitemap date rather than making every page look newly revised.</p></> },
      { id: "writing", title: "How we write for players", content: <><p>Every practical page begins with the player&apos;s problem, not a keyword list. Instructions use a clear order, observable success checks and a safe fallback. A troubleshooting step should state what symptom it addresses, what result to expect and when to stop.</p><p>Internal links connect the next useful decision—such as moving from a beginner step to the tool guide, from a character page to relationship context, or from a symptom to a focused fix. They are not added merely to repeat the same paragraph across multiple pages.</p></> },
      { id: "corrections", title: "Corrections and update process", content: <><p>A correction is strongest when it includes the page URL, game version, platform, starting state, exact steps, observed result and whether the result repeats. We compare the report with existing evidence and update settled errors promptly. A claim that cannot yet be reproduced may remain labeled as a report rather than being discarded or promoted to fact.</p><p>Substantive changes are reflected in the visible review date. Minor spelling or layout adjustments do not imply that every factual statement was retested.</p></> },
      { id: "independence", title: "Independence, links and commercial transparency", content: <><p>This site is not affiliated with, endorsed by or operated by Gator Dragon Games. We do not receive access to private builds and cannot speak for future development plans. Links to Steam, itch.io, GitHub and community discussions are direct reference links so readers can check the relevant source or reach the proper provider.</p><p>The current site does not present paid placements, sponsored rankings or affiliate redirects. If that changes, commercial relationships should be disclosed near the affected content and should not determine factual conclusions.</p></> },
      { id: "limitations", title: "What this site cannot do", content: <><p>We cannot issue refunds, recover store accounts, supply game keys, provide official bug support, promise release dates, authorize third-party media use or guarantee that a mod remains compatible. Those requests belong with the developer, storefront, platform or project owner.</p><p>We also do not host pirated downloads, extracted scene packs or unauthorized game assets. Purchase and download guidance points to identified official stores or a clearly labeled third-party project page.</p></> },
      { id: "contact", title: "Help us keep it accurate", content: <><p>If a current-build result differs from a page, send the page URL, game version, platform and reproducible steps to <a href={`mailto:${email}`}>{email}</a>. For accessibility or layout problems, include the browser, screen size and the task you could not complete.</p><p>Messages are evidence to review, not an automatic license to publish private correspondence or personal details. See Contact Us for the best format and the Privacy Policy for how email information is handled.</p></> },
    ],
  },
  contact: {
    eyebrow: "CONTACT & CORRECTIONS",
    keyword: "DRAG'N WASH GUIDE",
    title: "CONTACT US",
    subtitle: "Send a correction, question or rights notice",
    lead: "Use the published email for factual corrections, broken links, accessibility feedback, privacy questions and copyright notices.",
    answer: <><p><strong>Last reviewed: September 2026.</strong> Email <a href={`mailto:${email}`}>{email}</a>. There is no contact form, public comment area, account system or support ticket portal on this website.</p><p>Choose a clear subject and include the page URL. Please send only the information needed to investigate the request.</p></>,
    sections: [
      { id: "channels", title: "One contact address, different request types", content: <><p>Use <a href={`mailto:${email}`}>{email}</a> for guide corrections, broken links, accessibility feedback, privacy requests, copyright notices, permission questions and responsible security reports. Helpful subject lines include “Guide Correction,” “Accessibility,” “Privacy Request,” “Copyright Notice” or “Security.”</p><p>This address belongs to the independent fan guide. It is not an official Drag&apos;n Wash support address and cannot access your Steam, itch.io or game account.</p></> },
      { id: "corrections", title: "Gameplay and guide corrections", content: <><p>Include the exact page URL, platform, game version or patch date, starting state, what the guide currently says, what you observed and the smallest sequence that reproduces the result. State whether you repeated the test and whether mods or altered files were active.</p><p>A non-graphic screenshot can help if it shows the relevant objective, setting or error and does not expose private account information. Do not send full game archives, save files containing sensitive information, unreleased builds or explicit media.</p><p>We cannot promise that every report will become a published instruction. Conflicting or non-repeatable results may remain labeled as a community report until stronger evidence is available.</p></> },
      { id: "site", title: "Broken links, layout and accessibility", content: <><p>For a broken link, unreadable section, keyboard-navigation problem, missing alternative text or device-specific layout issue, include the URL, browser, operating system, approximate viewport size and the task you were trying to complete. Describe what appeared and what you expected.</p><p>Accessibility feedback is welcome even when you do not know the technical cause. We may ask a follow-up question to reproduce the barrier before changing a shared component.</p></> },
      { id: "privacy", title: "Privacy requests", content: <><p>Use the subject “Privacy Request” and identify the right you want to exercise. If the request concerns an earlier email, provide the sending address, approximate date and subject so it can be located. Do not send identity documents unless specifically requested and necessary; proportionate verification may be required before personal information is disclosed or deleted.</p><p>The Privacy Policy explains available rights, purposes, retention and complaint options. Rights depend on applicable law, and some records may need to be retained for security, legal claims or compliance.</p></> },
      { id: "copyright", title: "Copyright and permission requests", content: <><p>A copyright notice should identify the protected work, the exact site URL and material at issue, your contact details, your authority to act, and the required good-faith and accuracy statements. The Copyright page lists the full notice elements and explains the review process.</p><p>For permission to reuse our original writing or custom graphics, describe the exact material, intended use, distribution and whether the use is commercial. We cannot grant permission for game-owned screenshots, characters, audio or branding.</p></> },
      { id: "security", title: "Responsible security reports", content: <><p>Use the subject “Security” and describe the affected URL, observed behavior, date and a minimal non-destructive reproduction. Do not access another person&apos;s information, disrupt availability, demand payment, publish sensitive details before review or send executable proof-of-concept files.</p><p>This contact path is not a bug-bounty program and does not promise payment, safe-harbor status or a fixed response time. Good-faith, non-destructive reports will be reviewed and routed as practical.</p></> },
      { id: "limits", title: "Requests we cannot fulfill", content: <><p>We cannot issue refunds, recover accounts, replace purchases, provide keys, remove content hosted by another service, offer official bug tracking, disclose unreleased dates, supply private builds or provide personalized legal advice. Contact the relevant storefront, developer, platform, host or qualified professional.</p><p>Never email passwords, one-time codes, payment-card details, government identifiers, private license keys or sensitive information unrelated to the request.</p></> },
      { id: "response", title: "What happens after you write", content: <><p>Messages are reviewed when practical. Clear requests with a URL and reproducible context are easier to investigate, but no fixed response or resolution time is guaranteed. We may ask for clarification, correct the page, label an unresolved report, refer you to the responsible third party or explain why no action is appropriate.</p><p>Sending email does not create an attorney-client, confidential adviser, customer-support, employment or partnership relationship. Information is handled as described in the Privacy Policy.</p></> },
    ],
  },
};

export default function LegalPage({ kind, path }: { kind: LegalKind; path: string }) {
  const page = content[kind];
  return <EditorialPage
    variant="reference"
    path={path}
    reviewedAt="2026-09-22"
    eyebrow={page.eyebrow}
    keyword={page.keyword}
    title={page.title}
    subtitle={page.subtitle}
    lead={page.lead}
    image="/images/og-image.png"
    imageAlt="Drag'n Wash Player Field Manual artwork"
    answer={page.answer}
    sections={page.sections}
    related={[
      { label: "Privacy Policy", href: "/legal/privacy-policy" },
      { label: "Terms of Service", href: "/legal/terms-of-service" },
      { label: "Copyright", href: "/legal/copyright" },
      { label: "About Us", href: "/legal/about-us" },
      { label: "Contact Us", href: "/legal/contact-us" },
    ]}
  />;
}
